### ISSUE TITLE
Anyway to run without ipython?

### ISSUE THREAD

**Issue by shilik** [sugiyamath/sentiment_ja#1]
Hi @sugiyamath 
I wonder if there any way to run you codes without using ipython?
I have tried to put the your sample codes in a a file, but it returns "No module named 'sentimentja'"

Any suggestion?

**Comment by sugiyamath** [comment]
The code works correctly without using ipython.
If you can't import sentimentja, you probably installed it by ```make``` command, and if so, you should activate the generated virtualenv before running the script. 

```sh
source venv/bin/activate
```

In addition, you need to disable GPU by specifying ```CUDA_VISIBLE_DEVICES=-1``` .

By the way, this project is only supported Linux.
